language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OUP6TVhFPvuaBZFr+BI0WKIHkJMgMVecRTsat+oQkrJwXlYJr7ghZAipraNm/CjFlw3pAOCFY83y/pNO01koj9UJGeQE6sotAkLM4qpE7y/biJYAkoUL5Wy7dkTJNar52bW6rpFB6FU6m+vWaDf9H6QKWkvN/uFFPfImx8C0Quc="

addons:
  coverity_scan:
    project:
      name: "konradrenner/stammdaten"
      description: "Your project description here"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command:
    branch_pattern:
