language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "IDbvI0VEqkmRLDWg6pNWQew1thq3+yvKHOKd/kjyClY3QchvWGVvEj3lDK/8x7s6GqC7i6QGa1A5sDFkQUG6rCyPEnGHTa1nlxpiMp2oNbvDEqCORAmh1gX3RktA3rcLKLXhG/pH+HI0plsczzOt69SN/sUOdSjqpi3Je12snDs="

addons:
  coverity_scan:
    project:
      name: "konradrenner/stammdaten"
      description: "Your project description here"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command:
    branch_pattern:
